# -*- coding: utf-8 -*-
"""Aula_15_desafio

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mFDAP4NxaBIC8zh2AR-M34x6NfLaeaMx

RESOLUÇÃO AULA 15
"""

#saque.py

import deposito

def saque():
     print("Digite o valor do saque")
     saque1 = float(input("digite  o valor do saque->"))
     sub =  deposito.value0 -  saque1
     print(f'Saldo em conta > {sub}')

#deposito.py

value0 = 0

def deposito():
    print("Digite o valor do deposito: ")
    value1 = (input("Digite aqui> "))
    value0 == value1
    print(f'O valor depositado foi R${value1}')

#main.py

import deposito
import saque

print("Para saque (S), para depositos(D)")
escolha  =  input(" Digite uma opção ")

def main():
    if escolha  ==  "s" or escolha == "S":
         deposito.deposito()
    else:
         saque.saque()



main()